ci:
  autofix_prs: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.288"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black
