# image data, apply a json schema and publish it together with the API
# endpoint.
name: Container-Release

on:
  push:
    branches:
      - add-container-release-workflow
  #   tags:
  #     - '*.*.*'

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup rhelocator
    steps:
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10

      - name: Get full Python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - uses: robinraju/release-downloader@v1.5
        with:
          latest: true
          fileName: "*.tar.gz"
      - name: Install rhelocator
        run: pip install rhelocator-0.1.0.tar.gz

  regions:
    needs: setup
    name: Get a list of aws regions
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      aws_region_list: ${{ steps.aws-list.outputs.list }}
    steps:
      - id: aws-list
        run: |
          AWS_REGIONS=$(poetry run python ./src/rhelocator/cli.py aws-regions)
          echo ::set-output name=list::AWS_REGIONS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  images:
    name: Create AWS image resource
    needs: regions
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      list: ${{ fromJson(needs.regions.outputs.aws_region_list) }}
    steps:
      - run: |
          for region in $list; do
            aws_hourly_images --region $region
          done
