
name: Update-Job

on:
  schedule: # run every sunday at midnight
    - cron: "0 0 * * 0"

jobs:
  update-testdata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # check out all branches
        fetch-depth: 0
    - name: Transform raw data into schema
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        poetry run cloudimagedirectory-transformer --origin.s3.aws.key-id="${AWS_ACCESS_KEY_ID}" --origin.s3.aws.access-key="${AWS_SECRET_ACCESS_KEY}" --origin.s3.path="raw" --destination.s3.path="test" --origin.s3.bucket "cloudx-json-bucket" --image.api.version "alpha-v1"
