
name: Update-Job

on:
  schedule: # run at midnight
    - cron: "0 0 * * *"
jobs:
  update-testdata:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/update_images/testdata
    steps:
    - uses: actions/checkout@v3
      with:
        # check out all branches
        fetch-depth: 0
    - name: Update cloud provider dumps
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      run: ./update.sh
    - name: Commit cloud provider dumps
      env:
        BRANCH_NAME: cloud_data_update
      run: |
        git checkout -b ${BRANCH_NAME}
        git config --global user.name Janine Olear
        git config --global user.email pninak@web.de
        git add .
        git commit -m "Automated cloud provider update $(date +%  F)"    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        delete-branch: true
        title: '[Update] cloud provider test data'
        body: |
          Update cloud provider test data
          - AWS
          - Azure
          - Google
        labels: |
          automated-testdata-update
        reviewers: miyunari
